name: inventory
description: Inventory app
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.5
  cupertino_icons: ^0.1.2
  provider: ^3.2.0
  flutter_staggered_grid_view: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true